#+startup: showeverything

* Packages
This section exports the code corresponding to =packages.el=.
** Help
To install a package with Doom you must declare them here and run =doom sync=
on the command line, then restart Emacs for the changes to take effect -- or
use =M-x doom/reload=.

To install SOME-PACKAGE from MELPA, ELPA or emacsmirror:
#+begin_src elisp :tangle no
(package! some-package)
#+end_src

To install a package directly from a remote git repo, you must specify a
=:recipe=. You'll find documentation on what =:recipe= accepts here:
#+begin_center
https://github.com/raxod502/straight.el#the-recipe-format
#+end_center

#+begin_src elisp :tangle no
(package! another-package
  :recipe (:host github :repo "username/repo"))
#+end_src

If the package you are trying to install does not contain a =PACKAGENAME.el=
file, or is located in a subdirectory of the repo, you'll need to specify
=:files= in the =:recipe=:
#+begin_src elisp :tangle no
(package! this-package
  :recipe (:host github :repo "username/repo"
           :files ("some-file.el" "src/lisp/*.el")))
#+end_src

If you'd like to disable a package included with Doom, you can do so here
with the =:disable= property:
#+begin_src elisp :tangle no
(package! builtin-package :disable t)
#+end_src

You can override the recipe of a built in package without having to specify
all the properties for `:recipe'. These will inherit the rest of its recipe
from Doom or MELPA/ELPA/Emacsmirror:
#+begin_src emacs-lisp :tangle no
(package! builtin-package :recipe (:nonrecursive t))
(package! builtin-package-2 :recipe (:repo "myfork/package"))
#+end_src

Specify a =:branch= to install a package from a particular branch or tag.
This is required for some packages whose default branch isn't =master=.
#+begin_src elisp :tangle no
(package! builtin-package :recipe (:branch "develop"))
#+end_src

Use =:pin= to specify a particular commit to install.
#+begin_src elisp :tangle no
(package! builtin-package :pin "1a2b3c4d5e")
#+end_src

Doom's packages are pinned to a specific commit and updated from release to
release. The =unpin!= macro allows you to unpin single packages.
#+begin_src elisp :tangle no
(unpin! pinned-package)
;; ...or multiple packages
(unpin! pinned-package another-pinned-package)
;; ...Or *all* packages (NOT RECOMMENDED; will likely break things)
(unpin! t)
#+end_src

** My packages
*** evil-snipe
Disable evil-snipe.
#+begin_src elisp :tangle packages.el
(package! evil-snipe :disable t)
#+end_src

*** fish-mode
#+begin_src elisp :tangle packages.el
(package! fish-mode)
#+end_src

*** gnuplot-mode
#+begin_src elisp :tangle packages.el
(package! gnuplot-mode)
#+end_src

*** hledger-mode
#+begin_src elisp :tangle packages.el
(package! hledger-mode)
#+end_src

*** lean 4
#+begin_src elisp :tangle packages.el
(package! lean4-mode
  :recipe (:host github :repo "leanprover/lean4-mode"))
#+end_src

* General
** Doom
Disable tangle on save.
#+begin_src elisp
(remove-hook 'org-mode-hook #'+literate-enable-recompile-h)
#+end_src
** Profile
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!

Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+begin_src elisp
(setq user-full-name "Jan Mas Rovira"
      user-mail-address "janmasrovira@gmail.com")
#+end_src

** Font
Doom exposes five (optional) variables for controlling fonts in Doom:

- =doom-font=: the primary font to use.
- =doom-variable-pitch-font=: a non-monospace font (where applicable).
- =doom-big-font=: used for =doom-big-font-mode=; use this for
   presentations or streaming.
- =doom-unicode-font=: for unicode glyphs.
- =doom-serif-font=: for the =fixed-pitch-serif= face.

See =C-h v doom-font= for documentation and more examples of what they
accept.
#+begin_src elisp
(setq doom-font (font-spec :family "SauceCodePro Nerd Font" :size 14.0))
(setq doom-unicode-font (font-spec :name "DejaVu Math TeX Gyre"))
(setq doom-font-increment 1.0)
(map! "C-M-+" #'doom/increase-font-size)
#+end_src
 If you or Emacs can't find your font, use =M-x describe-font= to look them
 up, =M-x eval-region= to execute elisp code, and =M-x doom/reload-font= to
 refresh your font settings.

** Base
#+begin_src elisp
(setq doom-localleader-key ",")
(setq-default evil-escape-key-sequence "fd")
(map! :leader
      "q q" #'kill-emacs)

(map! :leader
      :desc "M-x"
      "SPC" #'execute-extended-command)

(map! :leader
      "r y" #'consult-yank-pop)

(+global-word-wrap-mode +1)
#+end_src

** Comments
#+begin_src elisp
(map!
      :leader "c l" #'evilnc-comment-or-uncomment-lines
      :leader "c y" #'evilnc-copy-and-comment-lines)
#+end_src

** Surround
#+begin_src elisp
(map! :v "s" #'evil-surround-region)
#+end_src

** Windows
#+begin_src elisp
(map! :leader "1" #'winum-select-window-1)
(map! :leader "2" #'winum-select-window-2)
(map! :leader "3" #'winum-select-window-3)
(map! :leader "4" #'winum-select-window-4)
(map! :leader "5" #'winum-select-window-5)
(map! :leader "6" #'winum-select-window-6)
(map! :leader "7" #'winum-select-window-7)
(map! :leader "8" #'winum-select-window-8)
(map! :leader "9" #'winum-select-window-9)
#+end_src

** Workspaces
#+begin_src elisp
(map! :leader "l l" #'+workspace/display)
(map! :leader "l n" #'+workspace/new)
(map! :leader "l k" #'+workspace/delete)
(map! :leader "l 1" #'+workspace/switch-to-0)
(map! :leader "l 2" #'+workspace/switch-to-1)
(map! :leader "l 3" #'+workspace/switch-to-2)
(map! :leader "l 4" #'+workspace/switch-to-3)
(map! :leader "l 5" #'+workspace/switch-to-4)
(map! :leader "l 6" #'+workspace/switch-to-5)
(map! :leader "l 7" #'+workspace/switch-to-6)
(map! :leader "l 8" #'+workspace/switch-to-7)
(map! :leader "l 9" #'+workspace/switch-to-8)
#+end_src

** Flycheck
#+begin_src elisp
(map! :map flycheck-mode-map :leader "e l" #'flycheck-list-errors)
(map! :map flycheck-mode-map :leader "e n" #'flycheck-next-error)
(map! :map flycheck-mode-map :leader "e p" #'flycheck-previous-error)
(use-package! flycheck-popup-tip
  :config
  (setq flycheck-popup-tip-error-prefix ""))
#+end_src

** Line numbers
This determines the style of line numbers in effect. If set to =nil=, line
numbers are disabled. For relative line numbers, set this to =relative=.
#+begin_src elisp
(setq display-line-numbers-type nil)
#+end_src

** Theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set =doom-theme= or manually load a theme with the
=load-theme= function. This is the default:
#+begin_src elisp
(setq doom-theme 'doom-one)
#+end_src
* Doom help
Whenever you reconfigure a package, make sure to wrap your config in an
=after!= block, otherwise Doom's defaults may override your settings. E.g.
#+begin_src elisp :tangle no
(after! PACKAGE
  (setq x y))
#+end_src
The exceptions to this rule:
- Setting file/directory variables (like `org-directory')
- Setting variables which explicitly tell you to set them before their
  package is loaded (see 'C-h v VARIABLE' to look up their documentation).
- Setting doom variables (which start with 'doom-' or '+').

Here are some additional functions/macros that will help you configure Doom.
- =load!= for loading external =*.el= files relative to this one.
- =use-package!= for configuring packages.
- =after!= for running code after a package has loaded.
- =add-load-path!=' for adding directories to the =load-path=, relative to
   this file. Emacs searches the =load-path= when you load packages with
   =require= or =use-package=.
- =map!= for binding new keys.

To get information about any of these functions/macros, move the cursor over the
highlighted symbol at press =K=. This will open documentation for it, including
demos of how they are used. Alternatively, use =C-h o= to look up a symbol
(functions, variables, faces, etc).

You can also try =gd= to jump to their definition and see how they are
implemented.

* Org
If you use =org= and don't want your org files in the default location below,
change =org-directory=. It must be set before org loads!
#+begin_src elisp
(setq org-directory "~/org/")
#+end_src

Edit code blocks with usual keybindings.
Misteriously this only work if you go into insert mode and then back to normal mode.
#+begin_src elisp
(map! :map org-src-mode-map
      :n ", c" #'org-edit-src-exit
      :n ", k" #'org-edit-src-abort)
#+end_src
* Agda
Require Agda input method if available.
#+begin_src elisp
(require 'agda-input nil t)
#+end_src

* Magit
Use Spacemacs keybindings.
#+begin_src elisp
(map! :leader "g s" #'magit-status)
(map! :localleader
      :map with-editor-mode-map
      "k" #'with-editor-cancel
      "c" #'with-editor-finish)
#+end_src

* Vertico
#+begin_src elisp
(map! :map vertico-map
      "C-h" #'vertico-directory-delete-char
      "C-l" #'vertico-directory-delete-word)
#+end_src

* Haskell
Map return for interactive mode.
#+begin_src elisp
(map!
   :map haskell-interactive-mode-map
   :n "RET" #'haskell-interactive-mode-return)
#+end_src

Disable suggestion for removing imports.
#+begin_src elisp
(after! haskell-mode
  (setq haskell-process-suggest-remove-import-lines nil))
#+end_src

Navigate the ghci history.
#+begin_src elisp
(map!
   :map haskell-interactive-mode-map
   :i "C-j" #'haskell-interactive-mode-history-next
   :i "C-k" #'haskell-interactive-mode-history-previous)
#+end_src


Fix: Allows to jump to an error from the interactive ghci buffer.
#+begin_src elisp
(after! haskell-mode
  (add-hook 'haskell-interactive-mode-hook
            (lambda ()
              (when (eq major-mode 'haskell-interactive-mode)
                (flycheck-mode +1)
                (flycheck-mode -1)
                ))))
#+end_src

Use Spacemacs keybindings.
#+begin_src elisp
(map! :localleader
      :map haskell-mode-map
      "'" #'haskell-interactive-switch
      "s c" #'haskell-interactive-mode-clear
      "l" #'haskell-process-load-file
      )
#+end_src

Disable the ghc checker.
#+begin_src elisp
(setq flycheck-disabled-checkers '(haskell-ghc haskell-stack-ghc))
#+end_src

* Hledger
#+begin_src elisp
(add-to-list 'auto-mode-alist '("\\.journal\\'" . hledger-mode))
(setq hledger-jfile "~/projects/balances/balances.journal")
#+end_src

* Avy
#+begin_src elisp
(map! :leader
      "j w" #'evil-avy-goto-word-or-subword-1
      )
#+end_src

* Project
#+begin_src elisp
(map! :leader "s a p"
      #'+default/search-project)
#+end_src

* Juvix
#+begin_src elisp
(push "~/projects/juvix/juvix-mode/" load-path)
(require 'juvix-mode nil t)
#+end_src
